### ISSUE TITLE
x2js should come bundled?

### ISSUE THREAD

**Issue by michahell** [johngeorgewright/angular-xml#34]
But... it doesn't if i use the exact bower install like mentioned on the readme.
x2js seems to be installable by bower so i went with that, and that works.
Just thought i'd let you know.

**Comment by johngeorgewright** [comment]
That's weird. Works just fine for me. It's defined as a dependency within the bower configuration.

**Comment by michahell** [comment]
Yeah weird. I thought it might be that i just had to include it, but there is no x2js file in the bower package when i browse the folder contents :/

**Comment by johngeorgewright** [comment]
It should install it as a separate package `bower_components/x2js`. I just tried it myself and it works OK. What OS are you on?

**Comment by michahell** [comment]
OSX 10.10 Yosemite. Weird thing is, i just uninstalled angular-xml and it said it had a dependency on x2js, so that should be correct indeed. Reinstalled and now it came through as a dependency, so all is good!
