### ISSUE TITLE
Specify which files to convert in the request?

### ISSUE THREAD

**Issue by bradyclifford** [johngeorgewright/angular-xml#35]
Is there a way to specify which files to convert and which files to let through as is?  Maybe the ability to add some req expressions to integrate the path and filename in the request?

**Comment by smromain** [comment]
You could potentially customize the http interceptor to do this. Right now, it just looks for whether it's an xml file or not, but you could potentially write your own custom one to delegate the response according to your needs.

**Comment by johngeorgewright** [comment]
I'm in the same mind as @smromain here. It's probably a bit out of the scope of this library for such a feature. However, you can either wrap the `xmlHttpInterceptor` or make an entirely new interceptor to achieve what you're asking.
