### ISSUE TITLE
Multiple elements in xml

### ISSUE THREAD

**Issue by bradrice** [johngeorgewright/angular-xml#36]
I have tried to use your example and add elements to the xml like so:

<blogs>
    <blog name="my first blog" id="1"/>
    <blog name="my second blog" id="2"/>
    <blog name="my third blog" id="3"/>
</blogs>

For some reason I can only get to the first element doing this:

$http.get('view1/blogs.xml').success(function (data) {
        $scope.blogs = data.blogs;
        console.log($scope.blogs);
    });

Is there a way to get it as an array of objects?

**Comment by johngeorgewright** [comment]
What does your XML look like?

**Comment by bradrice** [comment]
Sorry, I forgot to quote my code and it disapeared

`<!-- blogs.xml -->`
`<blogs>`
   ` <blog name="my first blog" id="1"/>`
    `<blog name="my second blog" id="2"/>`
    `<blog name="my third blog" id="3"/>`
`</blogs>`

**Comment by johngeorgewright** [comment]
If you want to see an array of `<blog/>`'s you can access them like so:

```js
$http.get('view1/blogs.xml').success(function (data) {
  console.log(data.blogs.blog);
});
```

**Comment by johngeorgewright** [comment]
I hope that has resolved your problem. There's more info on the [X2JS repo](https://code.google.com/p/x2js/wiki/BasicUsage) on how to use their service.
