### ISSUE TITLE
How to send XML?

### ISSUE THREAD

**Issue by rasmi** [johngeorgewright/angular-xml#37]
Is it currently possible to specify an option or flag in $http.get() that sends JSON array requests as XML, or should I manually convert using x2js and then send?

**Comment by johngeorgewright** [comment]
There isn't yet. Maybe we could have an interceptor for that? Until then, it'll have to be done manually I'm afraid.

**Comment by rasmi** [comment]
It isn't too big of an issue, actually. Manually parsing and serializing the data allows for some finer control  and formatting that the API I'm working with requires. I imagine automating it would only work in cases where the server was well-behaved.
